name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v4
        with:
          name: epub
          path: build/*.epub

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: dist/**/*.*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: npm run deploy
